sudo: required
dist: trusty

language: python
python:
- '3.5'

install:
- travis_retry wget https://github.com/novafloss/ansible-setup/archive/master.tar.gz
- tar xfvz master.tar.gz
- pushd ansible-setup-master && SETUP_LXD=1 DEBUG=1 ./setup.sh && popd

script:
- sg lxd '~/.ansible-env/bin/ansible-playbook -v test.yml -e test_lxc=0'

branches:
  except:
  - master
